"""add user settings table

Revision ID: b75e1bdc2cd5
Revises: 4baf41bc20b3
Create Date: 2025-11-04 19:57:31.592449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75e1bdc2cd5'
down_revision: Union[str, None] = '4baf41bc20b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
